leftnav:
- identifier: 04aa8e34-e482-f90a-7cc5-e6709235baa5
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: ea34c490-351d-2fbd-65a2-e59ad2a40de2
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 015a7d03-6d9c-2c3e-dfc3-30536cbe2854
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: a12209c7-40e6-ae18-5fad-4daa3dd035ce
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 96c1f79f-78ae-eb0f-69ab-841c65886c7d
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
